export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const GET_NEXT5_INITIATE = 'GET_NEXT5_INITIATE';
export const GET_NEXT5_SUCCESS = 'GET_NEXT5_SUCCESS';
export const GET_NEXT5_FAIL = 'GET_NEXT5_FAIL';
export const GET_RACE_INITIATE = 'GET_RACE_INITIATE';
export const GET_RACE_SUCCESS = 'GET_RACE_SUCCESS';
export const GET_RACE_FAIL = 'GET_RACE_FAIL';
